// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrvvfupuponmgnbjdifo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ydnZmdXB1cG9ubWduYmpkaWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDMyMTUsImV4cCI6MjA3MTY3OTIxNX0.fnyDS7_o8D5CEgNoFnpqXRj-wFErvSpUMRURKRLyfy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});